apiVersion: v1
kind: Service
metadata:
  name: media
spec:
  type: {{ .Values.service.type }}
  selector:
    app: media
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8086
      name: http
