apiVersion: v1
kind: Service
metadata:
  name: catalog
spec:
  type: {{ .Values.service.type }}
  selector:
    app: catalog
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8081
      name: http


